### ISSUE TITLE
翻译完文件显示文件占用的问题

### ISSUE THREAD

**Issue by seonwee** [Ding-Kyoma/EasyTrans-mac#10]
![image](https://github.com/Ding-Kyoma/EasyTrans-mac/assets/61080587/cd2d9309-084f-4145-81cd-8a831c584646)

**Comment by Ding-Kyoma** [comment]
应该是正常成功翻译的，请检查output文件夹。报错的原因是可能因为打开了原文件，所以不能将原文件移到output文件夹。若无其他问题，之后将正确handing这个exception
