### ISSUE TITLE
使用后发现有两个问题

### ISSUE THREAD

**Issue by b64406620** [Ding-Kyoma/EasyTrans-mac#13]
一是对表格的处理不是很好，二是生成的pdf文件占用空间较大，3页pdf就5M了。
以上两点能改进下吗？  
最后感谢作者无私开源精神

**Comment by Ding-Kyoma** [comment]
表格本身就很难处理。
文件大可能是因为有图片，可以试试无图模式，在main.py 中将第35行改为`save_img = False`

**Comment by b64406620** [comment]
> 表格本身就很难处理。 文件大可能是因为有图片，可以试试无图模式，在main.py 中将第35行改为`save_img = False`

但是看到原版的pdf才300多k，翻译后直接5M了，有点不科学

**Comment by Ding-Kyoma** [comment]
对于图片，重新嵌入到导出pdf的格式为png无损图片，若原pdf内为jpg压缩图片，则导出文件会大于原文件。

保存的时候为了兼容性考虑，压缩不是最高档 。main.py中line 345是保存的压缩等参数。实测若设置比较高时，有时候会保存报错。若想用更高的压缩比率，可以根据下面文档调整保存参数

save参数文档：https://pymupdf.readthedocs.io/en/latest/document.html#Document.save

文件过大的原因大概率是图片格式的转换所导致的。

**Comment by b64406620** [comment]
> 对于图片，重新嵌入到导出pdf的格式为png无损图片，若原pdf内为jpg压缩图片，则导出文件会大于原文件。
> 
> 保存的时候为了兼容性考虑，压缩不是最高档 。main.py中line 345是保存的压缩等参数。实测若设置比较高时，有时候会保存报错。若想用更高的压缩比率，可以根据下面文档调整保存参数
> 
> save参数文档：https://pymupdf.readthedocs.io/en/latest/document.html#Document.save
> 
> 文件过大的原因大概率是图片格式的转换所导致的。

我试着保存了一个没有图的pdf，占用空间大小是5.56M，有图的pdf，占用空间大小是5.87M 
![01851DF3](https://github.com/Ding-Kyoma/EasyTrans-mac/assets/23151246/e3318bf9-8017-4382-9c09-5f608960399b)
