### ISSUE TITLE
希望能支持目录格式，让每个子标题能符合原来格式

### ISSUE THREAD

**Issue by codeofyu** [Ding-Kyoma/EasyTrans-mac#4]
功能现在翻译文献可以，但是对大的文献教材书籍，还有些小缺陷，格式无法完美映射。期望强大的作者可以优化一下完美了。
[Roy J. Lewicki、Bruce Barry、 David M. Saunders - Essentials of Negotiation-McGraw-Hill Education (2016).pdf](https://github.com/Ding-Kyoma/EasyTrans-mac/files/8840958/Roy.J.Lewicki.Bruce.Barry.David.M.Saunders.-.Essentials.of.Negotiation-McGraw-Hill.Education.2016.pdf)
[Roy J. Lewicki、Bruce Barry、 David M. Saunders - Essentials of Negotiation-McGraw-Hill Education (2016)_translated.pdf](https://github.com/Ding-Kyoma/EasyTrans-mac/files/8840959/Roy.J.Lewicki.Bruce.Barry.David.M.Saunders.-.Essentials.of.Negotiation-McGraw-Hill.Education.2016._translated.pdf)

**Comment by Ding-Kyoma** [comment]
这部分功能是PyMuPDF实现的，很难优化……
