### ISSUE TITLE
包依赖冲突

### ISSUE THREAD

**Issue by setupdata** [Ding-Kyoma/EasyTrans-mac#5]
ERROR: Cannot install -r requirements.txt (line 8) and charset-normalizer==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested charset-normalizer==2.1.0
    requests 2.27.1 depends on charset-normalizer~=2.0.0; python_version >= "3"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
requests版本换成2.28.1解决问题。

**Comment by Ding-Kyoma** [comment]
谢谢提醒，已更正
