### ISSUE TITLE
翻译进度条完成之后不会保存文件

### ISSUE THREAD

**Issue by 6ChenY** [Ding-Kyoma/EasyTrans-mac#9]
文件中所有文字翻译完成之后，没有执行到保存文件的操作

**Comment by Ding-Kyoma** [comment]
终端里最后输出了什么？output_file 文件夹里没有任何东西么？

**Comment by 6ChenY** [comment]
是的，跑作者原来的文件，就只会卡在进度条100%之后就没有任何显示了

然后我试了一下自己创建了一个pdf(只包含了一句话), 可以输出文件，但是输出的文件当中pdf格式的翻译文件没有任何东西，txt有翻译后的内容

**Comment by Ding-Kyoma** [comment]
可能是环境问题或者是库没装好，请检查python版本与PyMuPDF版本。保存pdf是由PyMuPDF库完成的，我解决不了。
